warning: in the working copy of 'public/assets/logos/foundry-logo-hot.svg', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/assets/logos/foundry-logo-hot.svg', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/billboard/css/style.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/billboard/css/style.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/billboard/demos/donut/css/style.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/billboard/demos/donut/css/style.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/billboard/demos/donut/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/billboard/demos/donut/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/billboard/demos/donut/js/app.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/billboard/demos/donut/js/app.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/billboard/demos/drilling/css/style.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/billboard/demos/drilling/css/style.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/billboard/demos/drilling/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/billboard/demos/drilling/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/billboard/demos/drilling/js/app.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/billboard/demos/drilling/js/app.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/billboard/demos/mini-golf/css/style.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/billboard/demos/mini-golf/css/style.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/billboard/demos/mini-golf/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/billboard/demos/mini-golf/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/billboard/demos/mini-golf/js/app.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/billboard/demos/mini-golf/js/app.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/billboard/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/billboard/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/billboard/js/app.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/billboard/js/app.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/boardroom.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/boardroom.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/noticeboard/css/style.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/noticeboard/css/style.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/noticeboard/demos/charity-walk/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/noticeboard/demos/charity-walk/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/noticeboard/demos/charity-walk/script.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/noticeboard/demos/charity-walk/script.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/noticeboard/demos/charity-walk/styles.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/noticeboard/demos/charity-walk/styles.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/noticeboard/demos/diner/README.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/noticeboard/demos/diner/README.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/noticeboard/demos/diner/css/style.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/noticeboard/demos/diner/css/style.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/noticeboard/demos/diner/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/noticeboard/demos/diner/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/noticeboard/demos/diner/js/app.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/noticeboard/demos/diner/js/app.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/noticeboard/demos/produce/README.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/noticeboard/demos/produce/README.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/noticeboard/demos/produce/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/noticeboard/demos/produce/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/noticeboard/demos/produce/script.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/noticeboard/demos/produce/script.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/noticeboard/demos/produce/styles.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/noticeboard/demos/produce/styles.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/noticeboard/demos/produce/styles.css.before-header-tweak.bak', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/noticeboard/demos/produce/styles.css.before-header-tweak.bak', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/noticeboard/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/noticeboard/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/skateboard/css/style.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/skateboard/css/style.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/skateboard/demos/florist/README.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/skateboard/demos/florist/README.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/skateboard/demos/florist/css/style.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/skateboard/demos/florist/css/style.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/skateboard/demos/florist/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/skateboard/demos/florist/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/skateboard/demos/florist/js/main.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/skateboard/demos/florist/js/main.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/skateboard/demos/florist/success.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/skateboard/demos/florist/success.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/skateboard/demos/pottery/assets/images/README.txt', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/skateboard/demos/pottery/assets/images/README.txt', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/skateboard/demos/pottery/css/style.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/skateboard/demos/pottery/css/style.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/skateboard/demos/pottery/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/skateboard/demos/pottery/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/skateboard/demos/pottery/js/app.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/skateboard/demos/pottery/js/app.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/skateboard/demos/tailor/README.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/skateboard/demos/tailor/README.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/skateboard/demos/tailor/css/main.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/skateboard/demos/tailor/css/main.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/skateboard/demos/tailor/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'foundry/public/boardroom/skateboard/demos/tailor/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/boardroom/skateboard/demos/tailor/js/app.js', LF will be replaced by CRLF the next time Git touches it
